### ISSUE TITLE
Volcano-scheduler panic when create pod and use pvc

### ISSUE THREAD

**Issue by kongkongk** [volcano-sh/volcano#1017]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

/kind bug

**What happened**: 
Volcano-scheduler panic when create pod and use pvc

![image](https://user-images.githubusercontent.com/22409667/91444992-13a5bc80-e8a8-11ea-8665-f07256bc31e7.png)

![image](https://user-images.githubusercontent.com/22409667/91445184-64b5b080-e8a8-11ea-89c4-d26ed9372e84.png)

```
I0827 12:56:27.146626       1 statement.go:227] After allocated Task <default/test> to Node <10.165.253.216>: idle <cpu 59670.00, memory 114347659264.00, attachable-volumes-csi-disk.csi.everest.io 58000.00, cce/eni 7000.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00>, used <cpu 4100.00, memory 11588861952.00>, releasing <cpu 0.00, memory 0.00>
I0827 12:56:27.146667       1 statement.go:245] Allocating operations ...
I0827 12:56:27.146677       1 statement.go:328] Committing operations ...
I0827 12:56:28.146860       1 panic.go:969] Leaving Allocate ...
I0827 12:56:28.156679       1 cache.go:177] Updating pod condition for default/test to (PodScheduled==False)
I0827 12:56:28.162092       1 session.go:156] Close Session 9cb84bee-b1f0-4a3b-b325-85b0cbbfb094
I0827 12:56:28.162128       1 event_handlers.go:216] Updated pod <default/test> in cache.
E0827 12:56:28.162197       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 409 [running]:
volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x160c540, 0x276ba40)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x160c540, 0x276ba40)
        /usr/local/go/src/runtime/panic.go:969 +0x166
volcano.sh/apollo/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling.(*volumeBinder).checkBindings(0xc00016dea0, 0xc000672400, 0x27ba750, 0x0, 0x0, 0x27ba750, 0x0, 0x0, 0x6fc23ac00, 0x3b9aca00, ...)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling/scheduler_binder.go:450 +0xc9
volcano.sh/apollo/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling.(*volumeBinder).BindPodVolumes.func2(0xc000593128, 0xc000593118, 0x2)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling/scheduler_binder.go:351 +0x6d
volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc000f55820, 0xc000de32e0, 0xc00062e780, 0x0, 0x0)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:434 +0x136
volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc000f55820, 0xc0005932e0, 0x0, 0x0)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:320 +0x87
volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait.Poll(0x3b9aca00, 0x6fc23ac00, 0xc0005932e0, 0x27ba750, 0x0)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:314 +0x4d
volcano.sh/apollo/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling.(*volumeBinder).BindPodVolumes(0xc00016dea0, 0xc000672400, 0x0, 0x0)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling/scheduler_binder.go:350 +0x42b
volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/cache.(*defaultVolumeBinder).BindVolumes(0xc000122798, 0xc000838700, 0x4a, 0x99)
        /home/lb/src/volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/cache/cache.go:226 +0x5c
volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/cache.(*SchedulerCache).BindVolumes(0xc000530180, 0xc000838700, 0xc0002f00d0, 0xc0006ba400)
        /home/lb/src/volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/cache/cache.go:566 +0x44
volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/framework.(*Statement).allocate(0xc000de3750, 0xc000838700, 0xc000bb5410, 0xe, 0x1, 0x1)
        /home/lb/src/volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/framework/statement.go:255 +0x5a
volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/framework.(*Statement).Commit(0xc000de3750)
        /home/lb/src/volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/framework/statement.go:336 +0x253
volcano.sh/apollo/pkg/scheduler/actions/allocate.(*allocateAction).Execute(0xc0001220a0, 0xc0001ae280)
        /home/lb/src/volcano.sh/apollo/pkg/scheduler/actions/allocate/allocate.go:233 +0x1797
volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc00039f200)
        /home/lb/src/volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/scheduler.go:84 +0x25b
volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00062b670)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00062b670, 0x3b9aca00, 0x0, 0x1, 0x0)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00062b670, 0x3b9aca00, 0x0)
        /home/lb/src/volcano.sh/apollo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run
        /home/lb/src/volcano.sh/apollo/vendor/volcano.sh/volcano/pkg/scheduler/scheduler.go:68 +0xd4
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13d6189]
```

**What you expected to happen**:
create job and use pvc, and run ok

**How to reproduce it (as minimally and precisely as possible)**:
Use the following yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    scheduling.k8s.io/group-name: test
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 100
    image: centos:latest
    imagePullPolicy: IfNotPresent
    name: test-0
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /tmp/test
      name: pvc-test
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-secret
  restartPolicy: Never
  schedulerName: volcano
  volumes:
  - name: pvc-test
    persistentVolumeClaim:
      claimName: sc-ssd-pvc
```

**Environment**:
- Volcano Version: release-0.4
- Kubernetes version (use `kubectl version`): v1.15.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):CentOS Linux 7
- Kernel (e.g. `uname -a`):3.10.0-1062.1.1.el7.x86_64
- Install tools:
- Others:

**Comment by k82cn** [comment]
@william-wang , please help to check this one.

**Comment by wpeng102** [comment]
Need move https://github.com/volcano-sh/volcano/blob/ad3a8a16157436ac9551bbad3be60183027f72b5/pkg/scheduler/cache/cache.go#L336  initialize code before use. 

Reproduce:
1) submit volcano job with pvc
2) create pv and pvc

**Comment by wpeng102** [comment]
https://github.com/volcano-sh/volcano/pull/1018

**Comment by william-wang** [comment]
Let's fix this issue today. @wpeng102

**Comment by hzxuzhonghu** [comment]
Fixed
