### ISSUE TITLE
volcano scheduler will panic when use nonexist pvc in vcjob

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1073]
log:

```
E0929 03:43:09.909213       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 341 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x168a780, 0x2744270)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x168a780, 0x2744270)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x168a780, 0x2744270)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/kubernetes/pkg/controller/volume/scheduling.(*volumeBinder).checkBindings(0xc0001c45a0, 0xc000cfa600, 0x2792080, 0x0, 0x0, 0x2792080, 0x0, 0x0, 0xc001f16540, 0xc0002830f0, ...)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling/scheduler_binder.go:521 +0xc9
k8s.io/kubernetes/pkg/controller/volume/scheduling.(*volumeBinder).BindPodVolumes.func2(0xc0002830f0, 0xc001f16540, 0x3b9aca00)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling/scheduler_binder.go:418 +0x6d
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc0002832b8, 0xc000283000, 0x0, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0018813e0, 0xc0002832b8, 0xc001f16480, 0x0, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:541 +0x13a
k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc0018813e0, 0xc0002832b8, 0x0, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:427 +0x87
k8s.io/apimachinery/pkg/util/wait.Poll(0x3b9aca00, 0x6fc23ac00, 0xc0002832b8, 0x2792080, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:421 +0x4d
k8s.io/kubernetes/pkg/controller/volume/scheduling.(*volumeBinder).BindPodVolumes(0xc0001c45a0, 0xc000cfa600, 0x0, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling/scheduler_binder.go:417 +0x3e2
volcano.sh/volcano/pkg/scheduler/cache.(*defaultVolumeBinder).BindVolumes(0xc000343d30, 0xc0004a9080, 0x4a, 0x99)
	/root/go/src/github.com/volcano-sh/volcano/pkg/scheduler/cache/cache.go:252 +0x59
volcano.sh/volcano/pkg/scheduler/cache.(*SchedulerCache).BindVolumes(0xc000802d80, 0xc0004a9080, 0xc001f25a00, 0xc0006a6e00)
	/root/go/src/github.com/volcano-sh/volcano/pkg/scheduler/cache/cache.go:594 +0x44
volcano.sh/volcano/pkg/scheduler/framework.(*Statement).allocate(0xc000283728, 0xc0004a9080, 0x1, 0xc0002834f0)
	/root/go/src/github.com/volcano-sh/volcano/pkg/scheduler/framework/statement.go:285 +0x5a
volcano.sh/volcano/pkg/scheduler/framework.(*Statement).Commit(0xc000283728)
	/root/go/src/github.com/volcano-sh/volcano/pkg/scheduler/framework/statement.go:381 +0xdc
volcano.sh/volcano/pkg/scheduler/actions/allocate.(*Action).Execute(0x2792080, 0xc000922280)
	/root/go/src/github.com/volcano-sh/volcano/pkg/scheduler/actions/allocate/allocate.go:247 +0x1953
volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc000132620)
	/root/go/src/github.com/volcano-sh/volcano/pkg/scheduler/scheduler.go:82 +0x25b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00177d530)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00177d530, 0x1afc5a0, 0xc001f02600, 0x1, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00177d530, 0x3b9aca00, 0x0, 0x195f701, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00177d530, 0x3b9aca00, 0x0)
	/root/go/src/github.com/volcano-sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run
	/root/go/src/github.com/volcano-sh/volcano/pkg/scheduler/scheduler.go:66 +0xd4
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14650b9]
```

volcano version: v1.0.1

**Comment by wangxf1987** [comment]
It's should be check the pvc state for the task.pod, that before return.

**Comment by hzxuzhonghu** [comment]
Looks duplicate with https://github.com/volcano-sh/volcano/issues/1017

**Comment by hzxuzhonghu** [comment]
@Thor-wl We need to release 1.0.2 to include the fix

**Comment by Thor-wl** [comment]
> @Thor-wl We need to release 1.0.2 to include the fix

OK. I will release a bug fix release recently.
