### ISSUE TITLE
ERROR：Message: admission webhook "validatepod.volcano.sh" denied the request: failed to get PodGroup for pod

### ISSUE THREAD

**Issue by dingzq01** [volcano-sh/volcano#1171]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Maybe is a BUG REPORT

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
- I have volcano installed as shown on the volcano website

- Compile the Spark-2.4-Volcan-0.1 branch under Huawei-CloudNative/Spark, and use the compiled file to make the image

- Use spark-submit to submit the Spark-Pi task, k8s default scheduler can perform the success, but once the specified on the command line "--conf spark.kubernetes.volcano.enable=true", it throws an exception:

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://apiserver.cluster.local:6443/api/v1/namespaces/default/pods. Message: admission webhook "validatepod.volcano.sh" denied the request: failed to get PodGroup for pod <default/spark-pi-1606898309030-driver>: podgroups.scheduling.volcano.sh "spark-pi-1606898309030-podgroup" not found. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=admission webhook "validatepod.volcano.sh" denied the request: failed to get PodGroup for pod <default/spark-pi-1606898309030-driver>: podgroups.scheduling.volcano.sh "spark-pi-1606898309030-podgroup" not found, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:503)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:442)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:406)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:365)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:234)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:796)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:326)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:322)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:142)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:141)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:141)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:267)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:258)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:258)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:221)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/12/02 16:38:30 INFO util.ShutdownHookManager: Shutdown hook called
20/12/02 16:38:30 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-930fa3d6-cdb6-40d2-8ef8-003edd71a2c2
```
I tried to change the version of Spark image to solve it, but it didn't work.

Here is log of volcano-admission
```
 I1202 08:37:54.156422       1 admit_pod.go:70] admitting pods -- CREATE
I1202 08:37:54.156713       1 schema.go:83] the pod struct is {TypeMeta:{Kind:Pod APIVersion:v1} ObjectMeta:{Name:spark-pi-1606898309030-driver GenerateName: Namespace:default SelfLink: UID:cfd83c80-d884-4fe1-816a-61de655df29c ResourceVersion: Generation:0 CreationTimestamp:2020-12-02 08:38:30 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[spark-app-selector:spark-c787f44c8cd04d56b9fb21c2ab3ceac8 spark-role:driver] Annotations:map[scheduling.k8s.io/group-name:spark-pi-1606898309030-podgroup volcano.sh/task-spec:spark-driver] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{Volumes:[{Name:spark-local-dir-1 VolumeSource:{HostPath:nil EmptyDir:&EmptyDirVolumeSource{Medium:,SizeLimit:<nil>,} GCEPersistentDisk:nil AWSElasticBlockStore:nil GitRepo:nil Secret:nil NFS:nil ISCSI:nil Glusterfs:nil PersistentVolumeClaim:nil RBD:nil FlexVolume:nil Cinder:nil CephFS:nil Flocker:nil DownwardAPI:nil FC:nil AzureFile:nil ConfigMap:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil Projected:nil PortworxVolume:nil ScaleIO:nil StorageOS:nil CSI:nil}} {Name:spark-conf-volume VolumeSource:{HostPath:nil EmptyDir:nil GCEPersistentDisk:nil AWSElasticBlockStore:nil GitRepo:nil Secret:nil NFS:nil ISCSI:nil Glusterfs:nil PersistentVolumeClaim:nil RBD:nil FlexVolume:nil Cinder:nil CephFS:nil Flocker:nil DownwardAPI:nil FC:nil AzureFile:nil ConfigMap:&ConfigMapVolumeSource{LocalObjectReference:LocalObjectReference{Name:spark-pi-1606898309030-driver-conf-map,},Items:[]KeyToPath{},DefaultMode:*420,Optional:nil,} VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil Projected:nil PortworxVolume:nil ScaleIO:nil StorageOS:nil CSI:nil}} {Name:spark-token-pkbcb VolumeSource:{HostPath:nil EmptyDir:nil GCEPersistentDisk:nil AWSElasticBlockStore:nil GitRepo:nil Secret:&SecretVolumeSource{SecretName:spark-token-pkbcb,Items:[]KeyToPath{},DefaultMode:nil,Optional:nil,} NFS:nil ISCSI:nil Glusterfs:nil PersistentVolumeClaim:nil RBD:nil FlexVolume:nil Cinder:nil CephFS:nil Flocker:nil DownwardAPI:nil FC:nil AzureFile:nil ConfigMap:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil Projected:nil PortworxVolume:nil ScaleIO:nil StorageOS:nil CSI:nil}}] InitContainers:[] Containers:[{Name:spark-kubernetes-driver Image:dingzq01/spark-volcano:2.4.3 Command:[] Args:[driver --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.examples.SparkPi spark-internal] WorkingDir: Ports:[{Name:driver-rpc-port HostPort:0 ContainerPort:7078 Protocol:TCP HostIP:} {Name:blockmanager HostPort:0 ContainerPort:7079 Protocol:TCP HostIP:} {Name:spark-ui HostPort:0 ContainerPort:4040 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:SPARK_DRIVER_BIND_ADDRESS Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:status.podIP,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {Name:SPARK_LOCAL_DIRS Value:/var/data/spark-5662a77e-4a10-40f7-90e4-57bd9582c893 ValueFrom:nil} {Name:SPARK_CONF_DIR Value:/opt/spark/conf ValueFrom:nil}] Resources:{Limits:map[memory:{i:{value:1476395008 scale:0} d:{Dec:<nil>} s: Format:BinarySI}] Requests:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:1476395008 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]} VolumeMounts:[{Name:spark-local-dir-1 ReadOnly:false MountPath:/var/data/spark-5662a77e-4a10-40f7-90e4-57bd9582c893 SubPath: MountPropagation:<nil> SubPathExpr:} {Name:spark-conf-volume ReadOnly:false MountPath:/opt/spark/conf SubPath: MountPropagation:<nil> SubPathExpr:} {Name:spark-token-pkbcb ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil> SubPathExpr:}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil StartupProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Never SecurityContext:nil Stdin:false StdinOnce:false TTY:false}] EphemeralContainers:[] RestartPolicy:Never TerminationGracePeriodSeconds:0xc00043dd80 ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccountName:spark DeprecatedServiceAccount:spark AutomountServiceAccountToken:<nil> NodeName: HostNetwork:false HostPID:false HostIPC:false ShareProcessNamespace:<nil> SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,FSGroupChangePolicy:nil,} ImagePullSecrets:[] Hostname: Subdomain: Affinity:nil SchedulerName:volcano Tolerations:[{Key:node.kubernetes.io/not-ready Operator:Exists Value: Effect:NoExecute TolerationSeconds:0xc00043de10} {Key:node.kubernetes.io/unreachable Operator:Exists Value: Effect:NoExecute TolerationSeconds:0xc00043de30}] HostAliases:[] PriorityClassName: Priority:0xc00043de40 DNSConfig:nil ReadinessGates:[] RuntimeClassName:<nil> EnableServiceLinks:0xc00043de44 PreemptionPolicy:<nil> Overhead:map[] TopologySpreadConstraints:[]} Status:{Phase:Pending Conditions:[] Message: Reason: NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:<nil> InitContainerStatuses:[] ContainerStatuses:[] QOSClass:Burstable EphemeralContainerStatuses:[]}}
I1202 08:37:54.159681       1 server.go:63] sending response: &AdmissionResponse{UID:,Allowed:false,Result:&v1.Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:failed to get PodGroup for pod <default/spark-pi-1606898309030-driver>: podgroups.scheduling.volcano.sh "spark-pi-1606898309030-podgroup" not found,Reason:,Details:nil,Code:0,},Patch:nil,PatchType:nil,AuditAnnotations:map[string]string{},}
```
Here is log of volcano-controllers
```
I1202 11:09:26.147868       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/queue/queue_controller.go:179: Watch close - *v1beta1.PodGroup total 0 items received
I1202 11:09:41.168163       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/podgroup/pg_controller.go:103: Watch close - *v1.Pod total 0 items received
I1202 11:09:41.174590       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:227: Watch close - *v1beta1.PriorityClass total 0 items received
I1202 11:09:45.132418       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:223: Watch close - *v1.PersistentVolumeClaim total 0 items received
I1202 11:10:25.140224       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:221: Watch close - *v1alpha1.Job total 0 items received
I1202 11:11:59.141622       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:226: Watch close - *v1alpha1.Command total 0 items received
I1202 11:12:28.161784       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/queue/queue_controller.go:180: Watch close - *v1alpha1.Command total 0 items received
I1202 11:12:31.086107       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/podgroup/pg_controller.go:104: Watch close - *v1beta1.PodGroup total 0 items received
I1202 11:12:54.071141       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/queue/queue_controller.go:178: Watch close - *v1beta1.Queue total 0 items received
I1202 11:14:21.119219       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:225: Watch close - *v1.Service total 0 items received
I1202 11:15:00.085121       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/garbagecollector/garbagecollector.go:94: Watch close - *v1alpha1.Job total 0 items received
I1202 11:15:35.141710       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:222: Watch close - *v1.Pod total 0 items received
I1202 11:15:43.112452       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:224: Watch close - *v1beta1.PodGroup total 0 items received
I1202 11:17:03.134448       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:223: Watch close - *v1.PersistentVolumeClaim total 0 items received
I1202 11:17:16.145131       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:226: Watch close - *v1alpha1.Command total 0 items received
I1202 11:18:07.173296       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/podgroup/pg_controller.go:103: Watch close - *v1.Pod total 0 items received
I1202 11:18:15.087916       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/podgroup/pg_controller.go:104: Watch close - *v1beta1.PodGroup total 0 items received
I1202 11:18:38.163763       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/queue/queue_controller.go:180: Watch close - *v1alpha1.Command total 0 items received
I1202 11:18:45.149447       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/queue/queue_controller.go:179: Watch close - *v1beta1.PodGroup total 0 items received
I1202 11:19:14.143098       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:221: Watch close - *v1alpha1.Job total 0 items received
I1202 11:19:27.177116       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:227: Watch close - *v1beta1.PriorityClass total 0 items received
I1202 11:20:01.072968       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/queue/queue_controller.go:178: Watch close - *v1beta1.Queue total 0 items received
I1202 11:21:57.087227       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/garbagecollector/garbagecollector.go:94: Watch close - *v1alpha1.Job total 0 items received
I1202 11:22:12.123326       1 reflector.go:495] volcano.sh/volcano/pkg/controllers/job/job_controller.go:225: Watch close - *v1.Service total 0 items received
```

**What you expected to happen**:
Expect to execute Spark-PI successfully

**How to reproduce it (as minimally and precisely as possible)**:
Compile the code for the Spark -2.4.3-volcano-0.1 branch of huawei-cloudnative/spark using the following command:
`./dev/make-distribution.sh --tgz -Phadoop-2.7 -Phive -Phive-thriftserver -Pyarn -Pkubernetes`

**Anything else we need to know?**:
Maybe these will be useful：
```
[root@master ~]# kubectl get all --all-namespaces
NAMESPACE        NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system      pod/calico-kube-controllers-564b6667d7-bq478            1/1     Running     0          20d
kube-system      pod/calico-node-8nnlf                                   1/1     Running     0          20d
kube-system      pod/calico-node-st6z9                                   1/1     Running     0          20d
kube-system      pod/calico-node-x5ms4                                   1/1     Running     0          20d
kube-system      pod/coredns-5644d7b6d9-4drcq                            1/1     Running     0          20d
kube-system      pod/coredns-5644d7b6d9-bhhmr                            1/1     Running     0          20d
kube-system      pod/etcd-master                                         1/1     Running     0          20d
kube-system      pod/kube-apiserver-master                               1/1     Running     0          20d
kube-system      pod/kube-controller-manager-master                      1/1     Running     2          20d
kube-system      pod/kube-proxy-2wcqc                                    1/1     Running     0          20d
kube-system      pod/kube-proxy-9z7r8                                    1/1     Running     0          20d
kube-system      pod/kube-proxy-f8fqh                                    1/1     Running     0          20d
kube-system      pod/kube-scheduler-master                               1/1     Running     0          20d
kube-system      pod/kube-sealyun-lvscare-node1                          1/1     Running     0          20d
kube-system      pod/kube-sealyun-lvscare-node2                          1/1     Running     0          20d
volcano-system   pod/volcano-admission-5f8d8f8cf8-rbkbz                  1/1     Running     0          2d23h
volcano-system   pod/volcano-admission-init-jmjxf                        0/1     Completed   0          7d23h
volcano-system   pod/volcano-controllers-846fb9786-lmr95                 1/1     Running     0          2d23h
volcano-system   pod/volcano-scheduler-6998546fdb-pxq9k                  1/1     Running     0          2d23h

NAMESPACE        NAME                                                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default          service/kubernetes                                              ClusterIP   10.96.0.1       <none>        443/TCP                  20d
kube-system      service/kube-dns                                                ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   20d
volcano-system   service/volcano-admission-service                               ClusterIP   10.107.189.74   <none>        443/TCP                  7d23h
volcano-system   service/volcano-scheduler-service                               ClusterIP   10.98.214.114   <none>        8080/TCP                 7d23h

NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
kube-system   daemonset.apps/calico-node   3         3         3       3            3           beta.kubernetes.io/os=linux   20d
kube-system   daemonset.apps/kube-proxy    3         3         3       3            3           beta.kubernetes.io/os=linux   20d

NAMESPACE        NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system      deployment.apps/calico-kube-controllers   1/1     1            1           20d
kube-system      deployment.apps/coredns                   2/2     2            2           20d
volcano-system   deployment.apps/volcano-admission         1/1     1            1           7d23h
volcano-system   deployment.apps/volcano-controllers       1/1     1            1           7d23h
volcano-system   deployment.apps/volcano-scheduler         1/1     1            1           7d23h

NAMESPACE        NAME                                                 DESIRED   CURRENT   READY   AGE
kube-system      replicaset.apps/calico-kube-controllers-564b6667d7   1         1         1       20d
kube-system      replicaset.apps/coredns-5644d7b6d9                   2         2         2       20d
volcano-system   replicaset.apps/volcano-admission-5f8d8f8cf8         1         1         1       2d23h
volcano-system   replicaset.apps/volcano-admission-8947c749           0         0         0       7d23h
volcano-system   replicaset.apps/volcano-controllers-7c7f665675       0         0         0       7d23h
volcano-system   replicaset.apps/volcano-controllers-846fb9786        1         1         1       2d23h
volcano-system   replicaset.apps/volcano-scheduler-5cd987686c         0         0         0       7d23h
volcano-system   replicaset.apps/volcano-scheduler-6998546fdb         1         1         1       2d23h

NAMESPACE        NAME                               COMPLETIONS   DURATION   AGE
volcano-system   job.batch/volcano-admission-init   1/1           2m33s      7d23h
```

**Environment**:
- Volcano Version:
v1.1.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
`Linux master 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by william-wang** [comment]
The cause is CRD version mismatch. The Spark-2.4-volcano-0.1 have not supported volcano v1.1.0 version yet. Please use volcano v0.3/v0.2 to have a try. @dingzq01

**Comment by william-wang** [comment]
@dingzq01 
There is CRD API version change from v0.3 to v0.4. The CRD API version have been stable after version 0.4 and will keep compability in the future.

Would you like to make a contribution to enable volcano 1.1.0 on spark?  The code merge/change is not complicated.  I will be glad if you can contribute that :)

**Comment by dingzq01** [comment]
@william-wang I am very glad to receive your reply! I'm trying to submit a job using a lower version of Volcano. But I'm not sure how to compile version 0.4 volcano and hope you can help.
Others,I feel very lucky to make a contribution to enable volcano 1.1.0 on spark，I'm willing to have a try if it's not complicated!I hope I don't disappoint you.

**Comment by william-wang** [comment]
@dingzq01 That's great you are willing to make contribution 👍.  I log a issue #1175 to track this.
For the 0.4 compime. Just hit "make images" under volcano directory.

**Comment by Thor-wl** [comment]
Is there any process about this issue? Any PR has already been submitted or merged?
