### ISSUE TITLE
Fail to install volcano on minikube

### ISSUE THREAD

**Issue by pingsutw** [volcano-sh/volcano#1664]
**What happened**:
Fail to install volcano on minikube.
```
$ kubectl describe pods volcano-admission-5f7b5f989-tcfhl -n volcano-system
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    52m                   default-scheduler  Successfully assigned volcano-system/volcano-admission-5f7b5f989-tcfhl to minikube
  Warning  FailedMount  51m (x7 over 52m)     kubelet            MountVolume.SetUp failed for volume "admission-certs" : secret "volcano-admission-secret" not found
  Normal   Pulled       50m (x4 over 51m)     kubelet            Container image "volcanosh/vc-webhook-manager:latest" already present on machine
  Normal   Created      50m (x4 over 51m)     kubelet            Created container admission
  Normal   Started      50m (x4 over 51m)     kubelet            Started container admission
  Warning  BackOff      118s (x229 over 51m)  kubelet            Back-off restarting failed container
```

```
$ kubectl get pods -A
grafana-54fc5b4959-4rhzt                 1/1     Running            0          60m
kube-state-metrics-75d7664b87-2gkg8      1/1     Running            0          60m
prometheus-deployment-7bb6c5d7fd-p4tff   1/1     Running            0          60m
volcano-admission-5f7b5f989-tcfhl        0/1     CrashLoopBackOff   16         60m
volcano-admission-init-p8rb2             0/1     Completed          0          60m
volcano-controllers-68d55f9444-9sn4f     1/1     Running            0          60m
volcano-scheduler-7cc766767b-m7n89       1/1     Running            0          60m
```

```
$ kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
Warning: resource clusterrolebindings/volcano-scheduler-role is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
clusterrolebinding.rbac.authorization.k8s.io/volcano-scheduler-role configured
Warning: resource services/volcano-scheduler-service is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
service/volcano-scheduler-service configured
Warning: resource deployments/volcano-scheduler is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.apps/volcano-scheduler configured
unable to recognize "https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

**What you expected to happen**:
`volcano-admission-5f7b5f989-tcfhl` should run successfully.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ minikube start --vm-driver=docker --cpus 8 --memory 4096 --kubernetes-version v1.15.11
$ kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
```
**Anything else we need to know?**:

**Environment**:
- Volcano Version: Latest
- Kubernetes version (use `kubectl version`): 1.15.11
- Cloud provider or hardware configuration: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): `Linux kobe-pc 5.4.0-77-generic #86~18.04.1-Ubuntu SMP Fri Jun 18 01:23:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools: 
- Others:

**Comment by shinytang6** [comment]
l believe it's the same issue with https://github.com/volcano-sh/volcano/issues/1638

**Comment by pingsutw** [comment]
I tried 1.3.0 and It doesn't work for me. 
`volcano-admission` runs successfully, but `volcano-scheduler` failed.
I got the below error.
```
(base) ➜  ~ k get pods -A
NAMESPACE        NAME                                  READY   STATUS      RESTARTS   AGE
kube-system      coredns-5644d7b6d9-dhnfb              1/1     Running     0          74s
kube-system      etcd-minikube                         1/1     Running     0          7s
kube-system      kube-apiserver-minikube               1/1     Running     0          27s
kube-system      kube-controller-manager-minikube      1/1     Running     0          8s
kube-system      kube-proxy-zxn4t                      1/1     Running     0          74s
kube-system      kube-scheduler-minikube               1/1     Running     0          26s
kube-system      storage-provisioner                   1/1     Running     1          87s
volcano-system   volcano-admission-5f8d8f8cf8-gxz4q    1/1     Running     0          66s
volcano-system   volcano-admission-init-sf5nv          0/1     Completed   0          66s
volcano-system   volcano-controllers-846fb9786-5tm5j   1/1     Running     0          66s
volcano-system   volcano-scheduler-6998546fdb-5sf92    0/1     Error       3          66s
```

```
(base) ➜  ~ k logs volcano-scheduler-6998546fdb-5sf92 -n volcano-system
W0809 15:36:55.480893       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
panic: failed init default queue, with err: Post "https://10.96.0.1:443/apis/scheduling.volcano.sh/v1beta1/queues": stream error: stream ID 1; INTERNAL_ERROR

goroutine 1 [running]:
volcano.sh/volcano/pkg/scheduler/cache.newSchedulerCache(0xc0003d3200, 0x1aef52d, 0x7, 0x1aee948, 0x7, 0x0)
	/usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/cache/cache.go:296 +0x21d7
volcano.sh/volcano/pkg/scheduler/cache.New(...)
	/usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/cache/cache.go:68
volcano.sh/volcano/pkg/scheduler.NewScheduler(0xc0003d3200, 0x1aef52d, 0x7, 0x7fffa10ceb35, 0x29, 0x3b9aca00, 0x1aee948, 0x7, 0x0, 0xc00022eb60, ...)
	/usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:73 +0x9c
volcano.sh/volcano/cmd/scheduler/app.Run(0xc00061e750, 0x1bb3650, 0x1bb3b70)
	/usr/wulei/go_projects/src/volcano.sh/volcano/cmd/scheduler/app/server.go:75 +0x209
main.main()
	/usr/wulei/go_projects/src/volcano.sh/volcano/cmd/scheduler/main.go:64 +0x1c5

```

**Comment by Thor-wl** [comment]
> I tried 1.3.0 and It doesn't work for me.
> `volcano-admission` runs successfully, but `volcano-scheduler` failed.
> I got the below error.
> 
> ```
> (base) ➜  ~ k get pods -A
> NAMESPACE        NAME                                  READY   STATUS      RESTARTS   AGE
> kube-system      coredns-5644d7b6d9-dhnfb              1/1     Running     0          74s
> kube-system      etcd-minikube                         1/1     Running     0          7s
> kube-system      kube-apiserver-minikube               1/1     Running     0          27s
> kube-system      kube-controller-manager-minikube      1/1     Running     0          8s
> kube-system      kube-proxy-zxn4t                      1/1     Running     0          74s
> kube-system      kube-scheduler-minikube               1/1     Running     0          26s
> kube-system      storage-provisioner                   1/1     Running     1          87s
> volcano-system   volcano-admission-5f8d8f8cf8-gxz4q    1/1     Running     0          66s
> volcano-system   volcano-admission-init-sf5nv          0/1     Completed   0          66s
> volcano-system   volcano-controllers-846fb9786-5tm5j   1/1     Running     0          66s
> volcano-system   volcano-scheduler-6998546fdb-5sf92    0/1     Error       3          66s
> ```
> 
> ```
> (base) ➜  ~ k logs volcano-scheduler-6998546fdb-5sf92 -n volcano-system
> W0809 15:36:55.480893       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> panic: failed init default queue, with err: Post "https://10.96.0.1:443/apis/scheduling.volcano.sh/v1beta1/queues": stream error: stream ID 1; INTERNAL_ERROR
> 
> goroutine 1 [running]:
> volcano.sh/volcano/pkg/scheduler/cache.newSchedulerCache(0xc0003d3200, 0x1aef52d, 0x7, 0x1aee948, 0x7, 0x0)
> 	/usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/cache/cache.go:296 +0x21d7
> volcano.sh/volcano/pkg/scheduler/cache.New(...)
> 	/usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/cache/cache.go:68
> volcano.sh/volcano/pkg/scheduler.NewScheduler(0xc0003d3200, 0x1aef52d, 0x7, 0x7fffa10ceb35, 0x29, 0x3b9aca00, 0x1aee948, 0x7, 0x0, 0xc00022eb60, ...)
> 	/usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:73 +0x9c
> volcano.sh/volcano/cmd/scheduler/app.Run(0xc00061e750, 0x1bb3650, 0x1bb3b70)
> 	/usr/wulei/go_projects/src/volcano.sh/volcano/cmd/scheduler/app/server.go:75 +0x209
> main.main()
> 	/usr/wulei/go_projects/src/volcano.sh/volcano/cmd/scheduler/main.go:64 +0x1c5
> ```

Please set --kubeconfig as a parameter for server and try again

**Comment by william-wang** [comment]
It's a configuration issue. Let's close it.
