### ISSUE TITLE
Error occur when execute the same task many times

### ISSUE THREAD

**Issue by a092cc** [volcano-sh/volcano#2633]
**What happened**:
When test the performance of spark-native integration with volcano,  when execute the same task with 50 times, interval is 3 seconds, half task failed.

**What you expected to happen**:
All task execute one by one and all of them should success.

**How to reproduce it (as minimally and precisely as possible)**:
Executing task by the following code.
```bash
#!/bin/bash
s=0
for ((i=1;i<=50;i=i+1))
do
     nohup ${SPARK_HOME1}/bin/spark-submit \
     --master k8s://https://xxx:6443 \
     --deploy-mode cluster \
     --class cn.cestc.test.JavaSparkReadHiveInHahadoopForComponent \
     --driver-cores 1 \
     --driver-memory 2G \
     --num-executors 1 \
     --executor-cores 1 \
     --executor-memory 2G \
     --name native_modetask2 \
     --jars hdfs://dev-host-03:8082/dolphinscheduler_arm/supportarm/resources/performance1/mysql-connector-java-8.0.29.jar \
     --conf spark.executor.instances=1 \
     --conf spark.kubernetes.namespace=support132x86 \
     --conf spark.kubernetes.authenticate.driver.serviceAccountName=support132x86 \
     --conf spark.kubernetes.container.image=xxx:85/public-release/spark-volcano:3.3.0  \
     --conf spark.kubernetes.scheduler.name=volcano  \
     --conf spark.kubernetes.scheduler.volcano.podGroupTemplateFile=/tmp/podgroup-template.yaml \
     --conf spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
     --conf spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
> log-$i.log &
     sleep 3s
done

```

podgroup-template.yaml
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
spec:
  # Specify minMember to 1 to make a driver pod
  minMember: 1
  # Specify minResources to support resource reservation (the driver pod resource and executors pod resource should be considered)
  # It is useful for ensource the available resources meet the minimum requirements of the Spark job and avoiding the
  # situation where drivers are scheduled, and then they are unable to schedule sufficient executors to progress.
  minResources:
    cpu: "10"
    memory: "20G"
  # Specify the priority, help users to specify job priority in the queue during scheduling.
  priorityClassName: system-node-critical
  # Specify the queue, indicates the resource queue which the job should be submitted to
  queue: support132x86 
```

**Anything else we need to know?**:
error task log
```
[INFO] 2022-12-29 16:46:15.060 [TaskLogInfo- - [taskAppId=TASK-7947514526080_14-1674-6086]-getOutputLogService]  -  -> 22/12/29 16:46:14 ERROR Client: Please check "kubectl auth can-i create pod" first. It should be yes.
	Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://xxx:6443/api/v1/namespaces/support132x86/pods. Message: admission webhook "validatepod.volcano.sh" denied the request: failed to create pod <support132x86/spkj-6086-driver> as the podgroup phase is Pending. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=admission webhook "validatepod.volcano.sh" denied the request: failed to create pod <support132x86/spkj-6086-driver> as the podgroup phase is Pending, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682)
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661)
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:612)
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555)
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518)
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:305)
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:644)
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:83)
		at io.fabric8.kubernetes.client.dsl.base.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:61)
		at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:152)
		at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$5(KubernetesClientApplication.scala:248)
		at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$5$adapted(KubernetesClientApplication.scala:242)
		at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2764)
		at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:242)
		at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:214)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	22/12/29 16:46:14 INFO ShutdownHookManager: Shutdown hook called
	22/12/29 16:46:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-8da822e9-7f18-433a-886e-eb8b56529792
[INFO] 2022-12-29 16:46:16.152 [TaskLogInfo- - [taskAppId=TASK-7947514526080_14-1674-6086]-getOutputLogService]  - FINALIZE_SESSION
[INFO] 2022-12-29 16:46:16.162 [TaskLogInfo- - [taskAppId=TASK-7947514526080_14-1674-6086]]  - process has exited, execute path:/tmp/dolphinschedu
```

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`):
```json
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):Linux master 5.4.121-1.el7.elrepo.x86_64 #1 SMP Thu May 20 19:22:37 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by Yikun** [comment]
cc @william-wang If  the podgroup is still `pending`, and a pod with specified podgroup is created, looks like webhook will prevent the pod creation?

**Comment by a092cc** [comment]
> 

Thanks for your reply, i install volcano on  2022.11.24 ,  use the link https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml download the volcano-development.yaml. At that time, [#2078](https://github.com/volcano-sh/volcano/pull/2078) has already been merged.

should i reinstall volcano on 1.6 or master again ?

**Comment by a092cc** [comment]
> 

```
2023/01/05 08:33:30 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
API Version: v1alpha1
Version: latest
Git SHA: d0d0cc4c7506be3c67c143c33047ce8e28a6f42d
Built At: 2022-01-06 01:21:29
Go Version: go1.17.5
Go OS/Arch: linux/amd64
```

**Comment by a092cc** [comment]
> 2\. 1.6.0
Thanks a lot, i will test 1.6.0 again.

**Comment by a092cc** [comment]
Thanks a lot, i will test 1.6.0 again.

**Comment by a092cc** [comment]
> 
This time, my version is v1.7.0， i will test the task next week

2023/01/06 10:50:04 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
API Version: v1alpha1
Version: v1.7.0
Git SHA: 1933d46bdc4434772518ebb74c4281671ddeffa1
Built At: 2023-01-04 09:08:59
Go Version: go1.19.1
Go OS/Arch: linux/amd64

**Comment by a092cc** [comment]
When use 1.7.0 submit the same task, task always pending, describe podgroup display the following info 
```
[root@master ~]# kubectl describe podgroup spark-405e0d91044b4e6c8f8fca6b44c8fcc8-podgroup -n support132x86
Name:         spark-405e0d91044b4e6c8f8fca6b44c8fcc8-podgroup
Namespace:    support132x86
Labels:       <none>
Annotations:  <none>
API Version:  scheduling.volcano.sh/v1beta1
Kind:         PodGroup
Metadata:
  Creation Timestamp:  2023-01-09T06:37:23Z
  Generation:          2
  Managed Fields:
    API Version:  scheduling.volcano.sh/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
      f:spec:
        .:
        f:minMember:
        f:minResources:
          .:
          f:cpu:
          f:memory:
        f:priorityClassName:
        f:queue:
    Manager:      okhttp
    Operation:    Update
    Time:         2023-01-09T06:37:23Z
    API Version:  scheduling.volcano.sh/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:phase:
    Manager:    Go-http-client
    Operation:  Update
    Time:       2023-01-09T06:37:24Z
  Owner References:
    API Version:     v1
    Controller:      true
    Kind:            Pod
    Name:            native-modetask2-0e378b85953f72ea-driver
    UID:             01325e6c-cf79-4957-8328-b8f44adf74a3
  Resource Version:  57427672
  Self Link:         /apis/scheduling.volcano.sh/v1beta1/namespaces/support132x86/podgroups/spark-405e0d91044b4e6c8f8fca6b44c8fcc8-podgroup
  UID:               0ef704fa-673a-4c09-9065-e5a2afb3b106
Spec:
  Min Member:  1
  Min Resources:
    Cpu:                2
    Memory:             3G
  Priority Class Name:  system-node-critical
  Queue:                support132x86
Status:
  Conditions:
    Last Transition Time:  2023-01-09T06:37:24Z
    Message:               1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable
    Reason:                NotEnoughResources
    Status:                True
    Transition ID:         8171ffdd-4112-4650-99ea-dd7dbc5bb3c2
    Type:                  Unschedulable
  Phase:                   Pending
Events:
  Type     Reason         Age                 From     Message
  ----     ------         ----                ----     -------
  Warning  Unschedulable  18s (x12 over 29s)  volcano  1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable
  Normal   Unschedulable  17s (x13 over 29s)  volcano  resource in cluster is overused
```

**Comment by a092cc** [comment]
I downgrade to 1.6.0, it works

**Comment by Thor-wl** [comment]
@a092cc Hi, according to the log output, I think the phase of podgroup keeps `pending` is caused by the insufficient cluster resource. Can you give more details about the usage of the cluster and the information about the queues? I guess you have configured `overcommit` plugin.

**Comment by a092cc** [comment]
> @a092cc Hi, according to the log output, I think the phase of podgroup keeps `pending` is caused by the insufficient cluster resource. Can you give more details about the usage of the cluster and the information about the queues? I guess you have configured `overcommit` plugin.

Hi @Thor-wl Thanks for your reply,  resource is sufficient, we have two work node, the rate of utilization(cpu and memory almost same) of each node is 7% and 20%.
I communicated with @wangyang0616 1.10 afternoon, we found, some pod had already Completed(and then delete by manual), but the podgroup still exists, and we guessed these podgroup occupy the minResource. when i found these podgroup and deleted them, the remaining pod start run one by one.

**Comment by Thor-wl** [comment]
> Hi @Thor-wl Thanks for your reply, resource is sufficient, we have two work node, the rate of utilization(cpu and memory almost same) of each node is 7% and 20%.
> 
> The same scene that all the pod pending occur on volcano 1.6.0 this time. part information of podgroup as bellow
> 
> ```
> Events:
>   Type     Reason         Age                 From     Message
>   ----     ------         ----                ----     -------
>   Warning  Unschedulable  18s (x12 over 29s)  volcano  1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable
>   Normal   Unschedulable  17s (x13 over 29s)  volcano  resource in cluster is overused
> ```
> 
> I communicated with @wangyang0616 1.10 afternoon, we found, some pod had already Completed(and then delete by manual), but the podgroup still exists, and we guessed these podgroup occupy the minResource. when i found these podgroup and deleted them, the remaining pod start run one by one.

@a092cc OK. If that, it is necessary to remove the minResource of completed podgroup from the queue by GC.

**Comment by wangyang0616** [comment]
This problem recurs in the local environment. After summary, the following two problems exist:

1. When Spark jobs are running, the `ownerreference `of podgroups is empty occasionally and cannot be queried by GC. When the status of podgroups is inqueue, resources in the queue are preoccupied. As a result, podgroups in subsequent queues remain pending and enqueue cannot be performed.

    As shown in the following figure, the number of pod groups and driver pods created by Spark jobs is five more pod groups than the number of driver pods. The diff comparison result shows that the ownerreference values of the five pod groups are empty.
    ```
    [root@volcano-10521-0li9z tmp]# kubectl get pod |grep driver |wc -l
    84
    [root@volcano-10521-0li9z tmp]# kubectl get pg |grep spark |wc -l
    89
    ```
    The information about a `podgroup `is as follows:
    ```
    [root@w00568049-volcano-10521-0li9z tmp]# kubectl describe pg spark-27eaad02bdb74075878b39c9921ead5a-podgroup
    Name:         spark-27eaad02bdb74075878b39c9921ead5a-podgroup
    Namespace:    default
    Labels:       <none>
    Annotations:  <none>
    API Version:  scheduling.volcano.sh/v1beta1
    Kind:         PodGroup
    Metadata:
      Creation Timestamp:  2023-01-18T09:04:14Z
      Generation:          989
      Managed Fields:
        API Version:  scheduling.volcano.sh/v1beta1
        Fields Type:  FieldsV1
        fieldsV1:
          f:spec:
            .:
            f:minMember:
            f:minResources:
              .:
              f:cpu:
              f:memory:
            f:queue:
        Manager:      okhttp
        Operation:    Update
        Time:         2023-01-18T09:04:14Z
        API Version:  scheduling.volcano.sh/v1beta1
        Fields Type:  FieldsV1
        fieldsV1:
          f:status:
            .:
            f:conditions:
            f:phase:
        Manager:         Go-http-client
        Operation:       Update
        Time:            2023-01-19T03:11:31Z
      Resource Version:  616568
      UID:               1731de64-f300-4471-97ec-4d6bffdc5167
    Spec:
      Min Member:  1
      Min Resources:
        Cpu:     3
        Memory:  6G
      Queue:     queue-wy
    Status:
      Conditions:
        Last Transition Time:  2023-01-19T03:11:31Z
        Message:               1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable
        Reason:                NotEnoughResources
        Status:                True
        Transition ID:         992c7088-7cd4-4cfc-ba63-11d324e24bc5
        Type:                  Unschedulable
      Phase:                   Inqueue
    Events:
      Type     Reason         Age                    From     Message
      ----     ------         ----                   ----     -------
      Warning  Unschedulable  109s (x3517 over 61m)  volcano  0/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable
    You have new mail in /var/spool/mail/root
    ```

    **Some scheduling logs：**
    ```
    I0119 10:10:24.328229       7 proportion.go:93] Considering Job <default/spark-b27899f4f4484a8dbd87ed241cd4cdf1-podgroup>.
    I0119 10:10:24.328242       7 proportion.go:159] Queue queue-wy allocated <cpu 1000.00, memory 1476395008.00> request <cpu 32000.00, memory 47244640256.00> inqueue <cpu 2000.00, memory 4523604992.00> elastic <cpu 0.00, memory 0.00>
    I0119 10:10:24.328248       7 proportion.go:93] Considering Job <default/spark-27eaad02bdb74075878b39c9921ead5a-podgroup>.
    I0119 10:10:24.328262       7 proportion.go:159] Queue queue-wy allocated <cpu 1000.00, memory 1476395008.00> request <cpu 32000.00, memory 47244640256.00> inqueue <cpu 5000.00, memory 10523604992.00> elastic <cpu 0.00, memory 0.00>
    ```
    ```
    I0119 10:10:25.386696       7 proportion.go:337] job spark-526e314cbf5b4a7ea652a72fdfb67c96-podgroup min resource <cpu 3000.00, memory 6000000000.00>, queue queue-wy capability <cpu 7000.00, memory 20197294080.00> allocated <cpu 1000.00, memory 1476395008.00> inqueue <cpu 5000.00, memory 10523604992.00> elastic <cpu 0.00, memory 0.00>
    I0119 10:10:25.386703       7 proportion.go:341] job spark-526e314cbf5b4a7ea652a72fdfb67c96-podgroup inqueue false
    ```


2. Some pods of Spark jobs are always in the `ContainerCreating `state because the configmap for running jobs is not automatically created. As a result, pods cannot be started. The pod groups corresponding to these jobs occupy queue resources and block enqueue of subsequent jobs. We need to analyze the reason why the Spark job configmap is not automatically created. Can you guide me to analyze it together? @Yikun 

    As shown in the following figure, the number of configmaps and driver pods created by Spark jobs is six more than that of configmaps. Driver pods without configmaps cannot be started.
    ```
    [root@volcano-10521-0li9z tmp]# kubectl get pod | grep driver |wc -l
    84
    [root@volcano-10521-0li9z tmp]# kubectl get cm | grep spark |wc -l
    78
    ```
    ```
    [root@volcano-10521-0li9z tmp]# kubectl describe pod spark-volcano-wy34-38924a85c41aebb0-driver
    Name:             spark-volcano-wy34-38924a85c41aebb0-driver
    Namespace:        default
    Priority:         0
    Service Account:  spark
    Node:             192.168.1.57/192.168.1.57
    Start Time:       Thu, 19 Jan 2023 09:20:46 +0800
    Labels:           spark-app-name=spark-volcano-wy34
                      spark-app-selector=spark-6df3696d31de44f5ae3e831ff6107fa2
                      spark-role=driver
                      spark-version=3.3.1
    Annotations:      scheduling.k8s.io/group-name: spark-6df3696d31de44f5ae3e831ff6107fa2-podgroup
    Status:           Pending
    IP:               
    IPs:              <none>
    Containers:
      spark-kubernetes-driver:
        Container ID:  
        Image:         wangyang0616/spark:spark-3.3.1-pyspark-volcano-wy1
        Image ID:      
        Ports:         7078/TCP, 7079/TCP, 4040/TCP
        Host Ports:    0/TCP, 0/TCP, 0/TCP
        Args:
          driver
          --properties-file
          /opt/spark/conf/spark.properties
          --class
          org.apache.spark.examples.SparkPi
          local:///opt/spark/examples/jars/spark-examples_2.12-3.3.1.jar
        State:          Waiting
          Reason:       ContainerCreating
        Ready:          False
        Restart Count:  0
        Limits:
          memory:  1408Mi
        Requests:
          cpu:     1
          memory:  1408Mi
        Environment:
          SPARK_USER:                 root
          SPARK_APPLICATION_ID:       spark-6df3696d31de44f5ae3e831ff6107fa2
          SPARK_DRIVER_BIND_ADDRESS:   (v1:status.podIP)
          SPARK_LOCAL_DIRS:           /var/data/spark-9760fe43-aae3-4014-b0d9-0ea047bfe1d8
          SPARK_CONF_DIR:             /opt/spark/conf
        Mounts:
          /opt/spark/conf from spark-conf-volume-driver (rw)
          /var/data/spark-9760fe43-aae3-4014-b0d9-0ea047bfe1d8 from spark-local-dir-1 (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7lmpk (ro)
    Conditions:
      Type              Status
      Initialized       True 
      Ready             False 
      ContainersReady   False 
      PodScheduled      True 
    Volumes:
      spark-local-dir-1:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:     
        SizeLimit:  <unset>
      spark-conf-volume-driver:
        Type:      ConfigMap (a volume populated by a ConfigMap)
        Name:      spark-drv-4b32f085c41ce116-conf-map
        Optional:  false
      kube-api-access-7lmpk:
        Type:                    Projected (a volume that contains injected data from multiple sources)
        TokenExpirationSeconds:  3607
        ConfigMapName:           kube-root-ca.crt
        ConfigMapOptional:       <nil>
        DownwardAPI:             true
    QoS Class:                   Burstable
    Node-Selectors:              <none>
    Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
    Events:
      Type     Reason       Age                    From     Message
      ----     ------       ----                   ----     -------
      Warning  FailedMount  29m (x10 over 115m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[spark-conf-volume-driver], unattached volumes=[kube-api-access-7lmpk spark-local-dir-1 spark-conf-volume-driver]: timed out waiting for the condition
      Warning  FailedMount  17m (x12 over 106m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[spark-conf-volume-driver], unattached volumes=[spark-conf-volume-driver kube-api-access-7lmpk spark-local-dir-1]: timed out waiting for the condition
      Warning  FailedMount  13m (x60 over 119m)    kubelet  MountVolume.SetUp failed for volume "spark-conf-volume-driver" : configmap "spark-drv-4b32f085c41ce116-conf-map" not found
      Warning  FailedMount  4m28s (x27 over 117m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[spark-conf-volume-driver], unattached volumes=[spark-local-dir-1 spark-conf-volume-driver kube-api-access-7lmpk]: timed out waiting for the condition
    ```

The problem can be reproduced locally as follows:
**queue.yaml**
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: queue-wy
spec:
  reclaimable: true
  weight: 1
  capability:
    cpu: "7"
```

**spark_performance.sh**
```
#!/bin/bash
s=0
for ((i=1;i<=100;i=i+1))
do
     nohup /home/wangyang/spark-3.3.1-bin-custom-spark/bin/spark-submit \
         --master k8s://https://192.168.1.35:5443 \
         --deploy-mode cluster \
         --driver-cores 1 \
         --driver-memory 1G \
         --num-executors 1 \
         --executor-cores 1 \
         --executor-memory 1G \
         --name spark-volcano-wy${i} \
         --class org.apache.spark.examples.SparkPi \
         --conf spark.executor.instances=1 \
         --conf spark.kubernetes.container.image=wangyang0616/spark:spark-3.3.1-pyspark-volcano-wy1 \
         --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
         --conf spark.kubernetes.scheduler.name=volcano  \
         --conf spark.kubernetes.scheduler.volcano.podGroupTemplateFile=/home/wangyang/podgroup-template.yaml \
         --conf spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
         --conf spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
         local:///opt/spark/examples/jars/spark-examples_2.12-3.3.1.jar &
    sleep 1s
done
```

**podgroup-template.yaml**
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
spec:
  # Specify minMember to 1 to make a driver pod
  minMember: 1
  # Specify minResources to support resource reservation (the driver pod resource and executors pod resource should be considered)
  # It is useful for ensource the available resources meet the minimum requirements of the Spark job and avoiding the
  # situation where drivers are scheduled, and then they are unable to schedule sufficient executors to progress.
  minResources:
    cpu: "3"
    memory: "6G"
  # Specify the queue, indicates the resource queue which the job should be submitted to
  queue: queue-wy
```

**Comment by a092cc** [comment]
> 

still reproducible or needed
