### ISSUE TITLE
NPE on vgpu.getGPUDeviceSnapShot when enabled vgpu on partial  node.

### ISSUE THREAD

**Issue by cnfatal** [volcano-sh/volcano#3141]
**What happened**:

```log
$ kubectl -n volcano-system logs -f volcano-scheduler-9c8989f88-cq54k  
...
I0925 09:53:44.260257       1 proportion.go:299] Queue <inference>: deserved <cpu 115200.00, memory 1072020062208.00, nvidia.com/gpu 12000.00>, allocated <cpu 115200.00, memory 1072020062208.00, nvidia.com/gpu 12000.00>, share <1>
I0925 09:53:44.260289       1 allocate.go:128] Queue <inference> is overused, ignore it.
I0925 09:53:44.260322       1 reclaim.go:49] There are <50> Jobs and <5> Queues in total for scheduling.
I0925 09:53:44.260555       1 proportion.go:299] Queue <harix>: deserved <cpu 0.00, memory 0.00>, allocated <cpu 0.00, memory 0.00>, share <0>
I0925 09:53:44.260584       1 reclaim.go:95] Queue <harix> is overused, ignore it.
I0925 09:53:44.260624       1 predicates.go:384] pod(default/gpu-pod) affinity require information is nil, plugin InterPodAffinity is skipped
I0925 09:53:44.260710       1 utils.go:256] counts= [{1 NVIDIA 1073741824 101 0}]
I0925 09:53:44.303254       1 session.go:240] Close Session 5af91c15-f522-4fad-b78f-091dfb8e041e
E0925 09:53:44.303458       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 405 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1de1620?, 0x35c4050})
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x35eabe0?})
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1de1620?, 0x35c4050?})
        /snap/go/10339/src/runtime/panic.go:914 +0x21f
volcano.sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu.getGPUDeviceSnapShot(...)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu/utils.go:308
volcano.sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu.checkNodeGPUSharingPredicate(0xc001c53200, 0x0, 0x1)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu/utils.go:340 +0x1ad
volcano.sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu.(*GPUDevices).FilterNode(0xc002b73180?, 0xc001c53200)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu/device_info.go:185 +0x119
volcano.sh/volcano/pkg/scheduler/plugins/predicates.(*predicatesPlugin).OnSessionOpen.func4(0xc002c98000, 0xc002320300)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/plugins/predicates/predicates.go:553 +0x12d6
volcano.sh/volcano/pkg/scheduler/framework.(*Session).PredicateFn(0xc00231e000, 0xc0021796e0?, 0xc000690400?)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/framework/session_plugins.go:615 +0x190
volcano.sh/volcano/pkg/scheduler/actions/reclaim.(*Action).Execute(0x20e74ef?, 0xc00231e000)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/actions/reclaim/reclaim.go:127 +0x128e
volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc000024dc0)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/scheduler.go:126 +0x38d
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x35c5da0?, {0x23c3300, 0xc002316780}, 0x1, 0xc0002014a0)
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bd1fb0?, 0x3b9aca00, 0x0, 0xd0?, 0x44503c?)
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(0x9e9885?, 0xc00044ee48?, 0xc000483fb8?)
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:161 +0x1e
created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run in goroutine 1
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/scheduler.go:95 +0x1cf
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16c410d]

goroutine 405 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x35eabe0?})
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x1de1620?, 0x35c4050?})
        /snap/go/10339/src/runtime/panic.go:914 +0x21f
volcano.sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu.getGPUDeviceSnapShot(...)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu/utils.go:308
volcano.sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu.checkNodeGPUSharingPredicate(0xc001c53200, 0x0, 0x1)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu/utils.go:340 +0x1ad
volcano.sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu.(*GPUDevices).FilterNode(0xc002b73180?, 0xc001c53200)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/api/devices/nvidia/vgpu/device_info.go:185 +0x119
volcano.sh/volcano/pkg/scheduler/plugins/predicates.(*predicatesPlugin).OnSessionOpen.func4(0xc002c98000, 0xc002320300)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/plugins/predicates/predicates.go:553 +0x12d6
volcano.sh/volcano/pkg/scheduler/framework.(*Session).PredicateFn(0xc00231e000, 0xc0021796e0?, 0xc000690400?)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/framework/session_plugins.go:615 +0x190
volcano.sh/volcano/pkg/scheduler/actions/reclaim.(*Action).Execute(0x20e74ef?, 0xc00231e000)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/actions/reclaim/reclaim.go:127 +0x128e
volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc000024dc0)
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/scheduler.go:126 +0x38d
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x35c5da0?, {0x23c3300, 0xc002316780}, 0x1, 0xc0002014a0)
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bd1fb0?, 0x3b9aca00, 0x0, 0xd0?, 0x44503c?)
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(0x9e9885?, 0xc00044ee48?, 0xc000483fb8?)
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:161 +0x1e
created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run in goroutine 1
        /home/user/workspace/github.com/volcano-sh/volcano/pkg/scheduler/scheduler.go:95 +0x1cf
```

**What you expected to happen**:

No NPE.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enabled VGPU in volcano config: `predicate.VGPUEnable: true` .
1. Enabled volcano-device-plugin with only some node  via set node selector on  daemon-set .
1. Restart secheduler.

**Anything else we need to know?**:

As the trace log says, It seems at :

https://github.com/volcano-sh/volcano/blob/14570c6f6278a9fc3a50202bfdc0e9b8a728a27f/pkg/scheduler/plugins/predicates/predicates.go#L550-L552

The `devices` var has type `*gpushare.GPUDevices` but `nil` value.

Add a log in code:
```go
	if devices, ok := node.Others[val].(api.Devices); ok {
		klog.Infof("-----Node Others [&#v], devices [%#v]", node.Others, devices)

		code, msg, err := devices.FilterNode(task.Pod)
``` 
Produce :
```log
I0925 10:23:29.727372       1 predicates.go:384] pod(default/gpu-pod) affinity require information is nil, plugin InterPodAffinity is skipped
I0925 10:23:29.727410       1 predicates.go:551] -----Node Others [map[string]interface {}{"GpuShare":(*gpushare.GPUDevices)(nil), "vgpu4pd":(*vgpu.GPUDevices)(nil)}], devices [(*gpushare.GPUDevices)(nil)]
I0925 10:23:29.727443       1 predicates.go:551] -----Node Others [map[string]interface {}{"GpuShare":(*gpushare.GPUDevices)(nil), "vgpu4pd":(*vgpu.GPUDevices)(nil)}], devices [(*vgpu.GPUDevices)(nil)]
I0925 10:23:29.727461       1 utils.go:256] counts= [{1 NVIDIA 1073741824 101 0}]
I0925 10:23:29.764442       1 session.go:240] Close Session 572826cd-8748-4673-a1b9-7393761797ca
E0925 10:23:29.764689       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 386 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1de1620?, 0x35c4050})
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x35eabe0?})
        /home/user/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:49 +0x6b
```

**Environment**:
- Volcano Version: v1.8.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cnfatal** [comment]
Update:

Cant passthrought `preempt` action event if has enough resources with `volcano.sh/vgpu-memory` requests limits set.

When:

1. Enable preempt and `volcano.sh/vgpu-memory` limit

Logs:

```log
I0926 03:06:24.991425       1 preempt.go:254] No validated victims on Node <l-xxx>: not enough resources: requested <cpu 1000.00, memory 1073741824.00, volcano.sh/vgpu-number 1000.00, volcano.sh/vgpu-memory 512000.00>, but future idle <cpu 111550.00, memory 1081148694528.00, ephemeral-storage 401638757326000.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00, nvidia.com/gpu 0.00, rdma/hca_shared_devices_a 0.00, volcano.sh/vgpu-number 80000.00>

```

Seems: 

https://github.com/volcano-sh/volcano/blob/0d6d3b6a0dee7fffbc4e71e41f758d6d206e92bb/pkg/scheduler/api/resource_info.go#L87-L99

at line 87 `volcano.sh/vgpu-memory` not pass  `v1helper.IsScalarResourceName`  check which maybe ignored?



I'm glad to help and contribute if I get feedback on how to improve this.

**Comment by Monokaix** [comment]
Fixed by https://github.com/volcano-sh/volcano/pull/3241
