### ISSUE TITLE
Volcano Queue Issues.

### ISSUE THREAD

**Issue by bubbybharath** [volcano-sh/volcano#3163]
Hi Team,

I have created a queue and podgroup, added --set batchScheduler.enable=true during spark operator deployment through helm. However, when i am testing a spark operator job, it is using the default queue and podgroup is generated with random values. Please let me know the process to use a custom queue and podgroup in spark operator.

podgroup-152df854-0b76-43d2-b4d3-9229ba1915e9
podgroup-6be9ba51-1579-4555-bc4c-efa76ac87d2d

1) Which version of spark operator support volcano? I tried using 3.3.2 i am not able to spin up the driver.. When I tried downloading spark operator 3.5.0 it looks good. However, the issue is with using custom queue and podgroup.

**Comment by hwdef** [comment]
@Yikun 

Please check this

**Comment by Yikun** [comment]
I am not very familar with spark operators, you can see [1] as reference. It seems

See also Apache Spark native vocano support: https://spark.apache.org/docs/latest/running-on-kubernetes.html#using-volcano-as-customized-scheduler-for-spark-on-kubernetes can specify the podgroup.

[1] https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/volcano-integration.md

**Comment by william-wang** [comment]
@bubbybharath It's reasonable to support specify  the custom queue, Would you like to tell us more about your scenario and use case?

**Comment by bubbybharath** [comment]
Hi,

I have attached the document here. My requirement is to create a custom
queue and podgroup and use it to spin up driver pod. I tried creating
podgroup within namespace and but it is randomly generating a pod group
name with default queue. Then I have started creating podgroup in the minio
bucket as podgroup template. Still it is not being picked up.

1) how to check if my podgroup is being used for the particular spark job?
The moment I see a driver spinned up, I also see a podgroup being created
with a dynamic name. I want to use the custom queue along with the pod
group.
2) which spark operator version is compatible with volcano? I tried using
3.3.2 but not working. When I used 3.5.0 it is working. Kindly assist me.

**Comment by bubbybharath** [comment]
[VolcanoIssues.docx](https://github.com/volcano-sh/volcano/files/13205239/VolcanoIssues.docx)

I have added the steps where I am unable to use custom queue and podgroup.

**Comment by bubbybharath** [comment]
@william-wang , please assist me

**Comment by Monokaix** [comment]
as far as I know, you can try to set `SparkApplicationSpec.Spec.BatchSchedulerOptions.Queue` field of SparkApplication to specify your custom queue name.

**Comment by bubbybharath** [comment]
we have added the below string in sparkapplication but no luck. Podgroup is using the default queue still.

sparkVersion: "3.5.0"
  batchScheduler: "volcano"
  batchSchedulerOptions:
    queue: "test-queue"

**Comment by bubbybharath** [comment]
Hi Team,

I am also trying to test volcano through spark submit command, getting the below error.

 Warning  SparkApplicationFailed  2m30s  spark-operator  SparkApplication sparkway-benchmark-testing failed: failed to run spark-submit for SparkApplication scp-corp-datahub-spark-ns/sparkway-benchmark-testing: 23/11/14 17:00:23 INFO SparkKubernetesClientFactory: Auto-configuring K8S client using current context from users K8S config file
Exception in thread "main" java.lang.ClassNotFoundException: org.apache.spark.deploy.k8s.features.VolcanoFeatureStep


I have added the below files as listed.

spark.kubernetes.scheduler.volcano.podGroupTemplateFile=s3a://scp-corp-etax/podgroups/test_podgroup.yaml spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep,

**Comment by apinchuk1** [comment]
I have noticed similar issue with spark submit job. It sends the job to the default queue no matter what. Looks like its not reading "spark.kubernetes.scheduler.volcano.podGroupTemplateFile" at all, because even when random name of a file is specified (a file that doesn't exist), no error is seen.

**Comment by apinchuk1** [comment]
@william-wang @Thor-wl 
I see there is similiar thread from 2021 [https://github.com/volcano-sh/volcano/issues/1462](url). Does volcano support custom queue for spark operator? I am seeing the same problem with spark operator, specifying custom queue, however jobs keep running in a default queue

**Comment by schauaib** [comment]
Hi, currently trying to use spark (3.5.0) with volcano but could not make my jobs reach custom queues, neither using spark-operator nor spark-submit command. Could someone make it work already ?
With spark-operator, I don't face any error but volcano simply ignore the custom queue requirement, whereas with spark-submit, I also face the  ClassNotFoundException about "VolcanoFeatureStep"...
Doesn't seem very mature stuff...

**Comment by Monokaix** [comment]
> Hi, currently trying to use spark (3.5.0) with volcano but could not make my jobs reach custom queues, neither using spark-operator nor spark-submit command. Could someone make it work already ? With spark-operator, I don't face any error but volcano simply ignore the custom queue requirement, whereas with spark-submit, I also face the ClassNotFoundException about "VolcanoFeatureStep"... Doesn't seem very mature stuff...

Hi, please refer to https://spark.apache.org/docs/latest/running-on-kubernetes.html#using-volcano-as-customized-scheduler-for-spark-on-kubernetes to submit your spark job, currently, set custom podgroup and queue is supported by spark-submit. And welcome to paste you spark config and error log if you have any problem.

**Comment by schauaib** [comment]
Thanks for your help. I finally made it work. I hadn't figured out that I had to rebuild a spark image to comply with Volcano. Now this seems ok

**Comment by danc** [comment]
Hi, I have the exact same issue, but can not find an end-to-end complete working description neither on spark nor on volcano documentation.
My current setup : 
- rebuilding spark distribution with 
ARG JAVA_VERSION=11
ARG SPARK_VERSION=3.4.1
ARG SCALA_VERSION=2.13
RUN git clone --depth 1 --branch v${SPARK_VERSION} https://github.com/apache/spark.git && cd spark && ./dev/change-scala-version.sh ${SCALA_VERSION} && ./dev/make-distribution.sh --name volcano-spark  --tgz -Pkubernetes -Pvolcano -Pscala-${SCALA_VERSION}

image including /opt/spark/work-dir/podgroup-test.yaml

Then with the built image using the following : 

kubectl -apply -f SparkApplication.yaml 

`apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  #generateName: spark-pi-
  namespace: default
spec:
  imagePullSecrets:
    - acr-auth  
  type: Scala
  mode: cluster
  image: our.repo/spark:volcano-latest
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.13-3.4.1.jar
  sparkVersion: 3.4.1
  sparkConf:
    spark.kubernetes.scheduler.name: volcano
    spark.kubernetes.scheduler.volcano.podGroupTemplateFile: /opt/spark/work-dir/podgroup-test.yaml
    spark.kubernetes.driver.pod.featureSteps: org.apache.spark.deploy.k8s.features.VolcanoFeatureStep
    spark.kubernetes.executor.pod.featureSteps: org.apache.spark.deploy.k8s.features.VolcanoFeatureStep
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: 1200m
    memory: 512m
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: 512m
  batchScheduler: "volcano" 
  batchSchedulerOptions:
    queue: "test"`


At this stage, the job runs correctly on the `default`queue when lines with VolcanoFeatureStep are commented, and the following error when they are uncommented:

Exception in thread "main" java.lang.ClassNotFoundException: org.apache.spark.deploy.k8s.features.VolcanoFeatureStep
  at java.base/java.net.URLClassLoader.findClass(Unknown Source)
  at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
  at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
  at java.base/java.lang.Class.forName0(Native Method)
  at java.base/java.lang.Class.forName(Unknown Source)
  at org.apache.spark.util.SparkClassUtils.classForName(SparkClassUtils.scala:41)
  at org.apache.spark.util.SparkClassUtils.classForName$(SparkClassUtils.scala:36)
  at org.apache.spark.util.Utils$.classForName(Utils.scala:94)
  at org.apache.spark.deploy.k8s.submit.KubernetesDriverBuilder.$anonfun$buildFromFeatures$3(KubernetesDriverBuilder.scala:43)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
  at org.apache.spark.deploy.k8s.submit.KubernetesDriverBuilder.buildFromFeatures(KubernetesDriverBuilder.scala:42)
  at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:104)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$6(KubernetesClientApplication.scala:256)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$6$adapted(KubernetesClientApplication.scala:250)
  at org.apache.spark.util.SparkErrorUtils.tryWithResource(SparkErrorUtils.scala:48)
  at org.apache.spark.util.SparkErrorUtils.tryWithResource$(SparkErrorUtils.scala:46)
  at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:94)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:250)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:223)
  at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
  at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
  at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
  at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
  at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by Nj-kol** [comment]
Has anyone able to run spark shell on volcano?
